config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/home', to:'static_pages#home'
  get '/help', to:'static_pages#help', as:'helf'
  get '/contact', to:'static_pages#contact'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  get '/login', to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy' 
  resources :users
  resources :account_activations, only: [:edit]
  resources :microposts, only:[:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
        @micropost = current_user.microposts.build 
        @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  
  def help
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
    <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <%= render 'shared/user_info' %>
            </section>
            <section class="micropost_form">
                <%= render "shared/micropost_form" %>
            </section>
        </aside>
        <div class="col-md-8">
            <h3>Micropost Feed</h3>
            <%= render 'shared/feed' %>
        </div>
    </div>
<% else %>
    <div class="text-center jumbotron">
        <%= link_to image_tag("blogging.svg", alt:"Rails logo", class: "img-responsive img-custom"), "http://www.facebook.com", target: "_blank"%>
        <h1>Welcome to the blog!</h1>
        <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>
<% end %>