config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/home', to:'static_pages#home'
  get '/help', to:'static_pages#help', as:'helf'
  get '/contact', to:'static_pages#contact'
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  get '/login', to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy' 
  resources :users
  resources :account_activations, only: [:edit]
  resources :microposts, only:[:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Blog", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
       <%= link_to "Home", root_path, class: "nav-item nav-link" %>
       <%= link_to "Help", helf_path, class: "nav-item nav-link" %>
       <% if logged_in? %>
        <%= link_to "Users", users_path , class: "nav-item nav-link" %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Profile", current_user, class: "dropdown-item" %>
              <%= link_to "Settings",edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", logout_path, method:"delete", class: "dropdown-item" %>
            </div>
        </li>
       <% else %>
           <%= link_to "Log in",login_path, class: "nav-item nav-link active" %>
       <% end %>
       
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class:"alert alert-#{message_type}") %>
        <% end %>
        <%= yield %>
        <div class="alert-success">
        <%= debug(params) if Rails.env.development? %>
        </div>
      </div>
     
  </body>
</html>